class CryptoImagesantsUrl {
  Map<String, String> cryptoImages = {
    "bitcoin": "assets/coinImages/bitcoin.svg",
    "ethereum": "assets/coinImages/ethereum.svg",
    "tether": "assets/coinImages/tether-usdt.svg",
    "bnb": "assets/coinImages/binance.svg",
    "usd-coin": "assets/coinImages/usdc.svg",
    "xrp": "assets/coinImages/xrp.svg",
    "solana": "assets/coinImages/solana.svg",
    "cardano": "assets/coinImages/cardano.svg",
    "avalanche": "assets/coinImages/avalanche.svg",
    "polkadot-new": "assets/coinImages/polkadot.svg",
    "terrausd": "assets/coinImages/terra-luna.svg",
    "shiba-inu": "assets/coinImages/shiba-inu.svg",
    "wrapped-bitcoin": "assets/coinImages/wrapped-bitcoin.svg",
    "near-protocol": "assets/coinImages/protocol.svg",
    "polygon": "assets/coinImages/polygon.svg",
    "cronos": "assets/coinImages/crypto-com.svg",
    "multi-collateral-dai": "assets/coinImages/multi-collateral-dai.svg",
    "litecoin": "assets/coinImages/litecoin.svg",
    "cosmos": "assets/coinImages/cosmos.svg",
    "chainlink": "assets/coinImages/chainlink.svg",
    "bitcoin-cash": "assets/coinImages/bitcoin-cash.svg",
    "uniswap": "assets/coinImages/uniswap.svg",
    "terra-luna": "assets/coinImages/terra-luna.svg",
    "tron": "assets/coinImages/tron.svg",
    "dogecoin": "assets/coinImages/dogecoin.svg",
    "binance-usd": "assets/coinImages/binance-usd.svg",
  };
}
